### ISSUE TITLE
Design Directory Search page

### ISSUE THREAD

**Issue by suninthesky** [thisisfieldworks/platform#12]
NGO, Foundations can view

Search by: Cause, Country, etc.

**Comment by chris-fw** [comment]
Cause / Country / Budget Size / Name

**Comment by chris-fw** [comment]
Hi Suraj - a suggestion - could we add Cause and Budget as a search option?  Or did you feel based on Beehive, these were well used / understood?

**Comment by suninthesky** [comment]
@chris-fw done. Was just using a few fields as an example. Actual inputs should be based on user research and available data to search on.
