### ISSUE TITLE
Copy for attributes listing page

### ISSUE THREAD

**Issue by suninthesky** [thisisfieldworks/platform#3]
[Mockup](https://xd.adobe.com/view/8fa04095-56b5-4382-9638-399656a3cc23/screen/0770ef5a-c407-4883-a1c2-2394e196f48c/Web-1280-Home-3?fullscreen)

**Comment by chris-fw** [comment]
**title**
Profiling Self-Assessment
**Instruction**
Honestly reflect on the different areas of your organisation and see what you can do to strengthen it.  Click on "Start Assessment" for each attribute and answer the statements.  At the end of each set of questions your level will appear and some information about the areas you can strengthen.
